% +--------------------------------------------------------------------------+
% | 'Indigo' module version 1.0 - BSD 3-Clause License - Copyright (c) 2023  |
% | Current version authors:                                                 |
% |   Davide Stocco and Enrico Bertolazzi.                                   |
% +--------------------------------------------------------------------------+

% Matlab generated code for implicit system: DoublePendulum
% This file has been automatically generated by Indigo.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef DoublePendulum < Indigo.Systems.Implicit
  %
  % No class description provided.
  %
  properties (SetAccess = protected, Hidden = true)
    % User data
    m_m = 1.0;
    m_g = 9.81;
    m_ell__1 = 1.0;
    m_ell__2 = 1.0;
  end
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = DoublePendulum( varargin )
      % Constructor for 'DoublePendulum' class.

      % Superclass constructor
      num_eqns = 10;
      num_veil = 0;
      num_invs = 6;
      this = this@Indigo.Systems.Implicit('DoublePendulum', num_eqns, num_veil, num_invs);

      % User data
      if (nargin == 0)
        % Keep default values
      elseif (nargin == 4)
        this.m_m = varargin{1};
        this.m_g = varargin{2};
        this.m_ell__1 = varargin{3};
        this.m_ell__2 = varargin{4};
      else
        error('wrong number of input arguments.');
      end
    end % DoublePendulum
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_F = F( this, in_1, in_2, in_3, t )
      % Evaluate the function F.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      u__1_dot = in_2(1);
      v__1_dot = in_2(2);
      u__2_dot = in_2(3);
      v__2_dot = in_2(4);
      x__1_dot = in_2(5);
      y__1_dot = in_2(6);
      x__2_dot = in_2(7);
      y__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      t5 = x__1 * lambda__1;
      t6 = 0.1e1 / m__1;
      t10 = g * m__1;
      t11 = y__1 * lambda__1;
      t17 = x__1 ^ 2;
      t18 = y__1 ^ 2;
      out_1 = -4 * u__1 * u__1_dot - 4 * v__1 * v__1_dot + 8 * x__1_dot * t6 * t5 + 2 * y__1_dot * t6 * (t10 + 4 * t11) + 4 * lambda__1_dot * t6 * (t17 + t18);
      t24 = -4 * u__1 - 4 * u__2;
      t27 = -4 * v__1 - 4 * v__2;
      t32 = lambda__2 * (x__2 + x__1);
      t33 = 0.1e1 / m__2;
      t38 = lambda__2 * y__1;
      t40 = lambda__2 * y__2;
      t43 = t33 * (g * m__2 + 4 * t38 + 4 * t40);
      t53 = x__2 ^ 2;
      t56 = y__2 ^ 2;
      out_2 = u__1_dot * t24 + v__1_dot * t27 + u__2_dot * t24 + v__2_dot * t27 + 8 * x__1_dot * t33 * t32 + 2 * y__1_dot * t43 + 8 * x__2_dot * t33 * t32 + 2 * y__2_dot * t43 + 4 * lambda__2_dot * t33 * (2 * x__2 * x__1 + 2 * y__1 * y__2 + t17 + t18 + t53 + t56);
      out_3 = x__1_dot - u__1;
      out_4 = y__1_dot - v__1;
      out_5 = x__2_dot - u__2;
      out_6 = y__2_dot - v__2;
      out_7 = 2 * t6 * m__2 * t5 + m__2 * u__1_dot;
      out_8 = m__2 * v__1_dot + t6 * (t10 + 2 * t11) * m__2;
      out_9 = -m__1 * u__2_dot - 2 * t33 * (x__1 * lambda__2 * m__1 + x__2 * lambda__2 * m__1 - m__2 * t5);
      out_10 = -m__1 * v__2_dot - 2 * t33 * (m__1 * t38 + m__1 * t40 - m__2 * t11);

      % Store outputs
      out_F = zeros(10, 1);
      out_F(1) = out_1;
      out_F(2) = out_2;
      out_F(3) = out_3;
      out_F(4) = out_4;
      out_F(5) = out_5;
      out_F(6) = out_6;
      out_F(7) = out_7;
      out_F(8) = out_8;
      out_F(9) = out_9;
      out_F(10) = out_10;
    end % F
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_x = JF_x( this, in_1, in_2, in_3, t )
      % Evaluate the Jacobian of F with respect to x.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      u__1_dot = in_2(1);
      v__1_dot = in_2(2);
      u__2_dot = in_2(3);
      v__2_dot = in_2(4);
      x__1_dot = in_2(5);
      y__1_dot = in_2(6);
      x__2_dot = in_2(7);
      y__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      out_1_1 = -4 * u__1_dot;
      out_2_1 = -4 * u__1_dot - 4 * u__2_dot;
      out_3_1 = -1;
      out_1_2 = -4 * v__1_dot;
      out_2_2 = -4 * v__1_dot - 4 * v__2_dot;
      out_4_2 = -1;
      out_2_3 = out_2_1;
      out_5_3 = -1;
      out_2_4 = out_2_2;
      out_6_4 = -1;
      t5 = 0.1e1 / m__1;
      t6 = t5 * lambda__1;
      t8 = t5 * x__1;
      out_1_5 = 8 * x__1_dot * t6 + 8 * lambda__1_dot * t8;
      t11 = 0.1e1 / m__2;
      t12 = t11 * lambda__2;
      t17 = x__2 + x__1;
      out_2_5 = 8 * lambda__2_dot * t11 * t17 + 8 * x__1_dot * t12 + 8 * x__2_dot * t12;
      t22 = lambda__1 * m__2;
      out_7_5 = 2 * t5 * t22;
      t24 = lambda__2 * m__1;
      out_9_5 = -2 * t11 * (t24 - t22);
      t29 = t5 * y__1;
      out_1_6 = 8 * lambda__1_dot * t29 + 8 * y__1_dot * t6;
      t36 = y__2 + y__1;
      out_2_6 = 8 * lambda__2_dot * t11 * t36 + 8 * y__1_dot * t12 + 8 * y__2_dot * t12;
      out_8_6 = out_7_5;
      out_10_6 = out_9_5;
      out_2_7 = out_2_5;
      out_9_7 = -2 * t11 * t24;
      out_2_8 = out_2_6;
      out_10_8 = out_9_7;
      out_1_9 = 8 * y__1_dot * t29 + 8 * x__1_dot * t8;
      out_7_9 = 2 * t5 * m__2 * x__1;
      out_8_9 = 2 * t5 * y__1 * m__2;
      out_9_9 = 2 * x__1;
      out_10_9 = 2 * y__1;
      t50 = t11 * t17;
      t54 = 4 * t11 * t36;
      out_2_10 = 8 * x__1_dot * t50 + 8 * x__2_dot * t50 + 2 * y__1_dot * t54 + 2 * y__2_dot * t54;
      out_9_10 = -2 * t11 * (x__1 * m__1 + x__2 * m__1);
      out_10_10 = -2 * t11 * (y__1 * m__1 + y__2 * m__1);

      % Store outputs
      out_JF_x = zeros(10, 10);
      out_JF_x(1, 1) = out_1_1;
      out_JF_x(2, 1) = out_2_1;
      out_JF_x(3, 1) = out_3_1;
      out_JF_x(1, 2) = out_1_2;
      out_JF_x(2, 2) = out_2_2;
      out_JF_x(4, 2) = out_4_2;
      out_JF_x(2, 3) = out_2_3;
      out_JF_x(5, 3) = out_5_3;
      out_JF_x(2, 4) = out_2_4;
      out_JF_x(6, 4) = out_6_4;
      out_JF_x(1, 5) = out_1_5;
      out_JF_x(2, 5) = out_2_5;
      out_JF_x(7, 5) = out_7_5;
      out_JF_x(9, 5) = out_9_5;
      out_JF_x(1, 6) = out_1_6;
      out_JF_x(2, 6) = out_2_6;
      out_JF_x(8, 6) = out_8_6;
      out_JF_x(10, 6) = out_10_6;
      out_JF_x(2, 7) = out_2_7;
      out_JF_x(9, 7) = out_9_7;
      out_JF_x(2, 8) = out_2_8;
      out_JF_x(10, 8) = out_10_8;
      out_JF_x(1, 9) = out_1_9;
      out_JF_x(7, 9) = out_7_9;
      out_JF_x(8, 9) = out_8_9;
      out_JF_x(9, 9) = out_9_9;
      out_JF_x(10, 9) = out_10_9;
      out_JF_x(2, 10) = out_2_10;
      out_JF_x(9, 10) = out_9_10;
      out_JF_x(10, 10) = out_10_10;
    end % JF_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_x_dot = JF_x_dot( this, in_1, in_2, in_3, t )
      % Evaluate the Jacobian of F with respect to x_dot.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      u__1_dot = in_2(1);
      v__1_dot = in_2(2);
      u__2_dot = in_2(3);
      v__2_dot = in_2(4);
      x__1_dot = in_2(5);
      y__1_dot = in_2(6);
      x__2_dot = in_2(7);
      y__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      out_1_1 = -4 * u__1;
      out_2_1 = -4 * u__1 - 4 * u__2;
      out_7_1 = m__2;
      out_1_2 = -4 * v__1;
      out_2_2 = -4 * v__1 - 4 * v__2;
      out_8_2 = m__2;
      out_2_3 = out_2_1;
      out_9_3 = -m__1;
      out_2_4 = out_2_2;
      out_10_4 = out_9_3;
      t6 = 0.1e1 / m__1;
      out_1_5 = 8 * t6 * lambda__1 * x__1;
      t10 = 0.1e1 / m__2;
      out_2_5 = 8 * t10 * (x__2 + x__1) * lambda__2;
      out_3_5 = 1;
      out_1_6 = 2 * t6 * (g * m__1 + 4 * y__1 * lambda__1);
      out_2_6 = 2 * t10 * (g * m__2 + 4 * y__1 * lambda__2 + 4 * y__2 * lambda__2);
      out_4_6 = 1;
      out_2_7 = out_2_5;
      out_5_7 = 1;
      out_2_8 = out_2_6;
      out_6_8 = 1;
      t24 = x__1 ^ 2;
      t25 = y__1 ^ 2;
      out_1_9 = 4 * t6 * (t24 + t25);
      t30 = x__2 ^ 2;
      t33 = y__2 ^ 2;
      out_2_10 = 4 * t10 * (2 * x__1 * x__2 + 2 * y__1 * y__2 + t24 + t25 + t30 + t33);

      % Store outputs
      out_JF_x_dot = zeros(10, 10);
      out_JF_x_dot(1, 1) = out_1_1;
      out_JF_x_dot(2, 1) = out_2_1;
      out_JF_x_dot(7, 1) = out_7_1;
      out_JF_x_dot(1, 2) = out_1_2;
      out_JF_x_dot(2, 2) = out_2_2;
      out_JF_x_dot(8, 2) = out_8_2;
      out_JF_x_dot(2, 3) = out_2_3;
      out_JF_x_dot(9, 3) = out_9_3;
      out_JF_x_dot(2, 4) = out_2_4;
      out_JF_x_dot(10, 4) = out_10_4;
      out_JF_x_dot(1, 5) = out_1_5;
      out_JF_x_dot(2, 5) = out_2_5;
      out_JF_x_dot(3, 5) = out_3_5;
      out_JF_x_dot(1, 6) = out_1_6;
      out_JF_x_dot(2, 6) = out_2_6;
      out_JF_x_dot(4, 6) = out_4_6;
      out_JF_x_dot(2, 7) = out_2_7;
      out_JF_x_dot(5, 7) = out_5_7;
      out_JF_x_dot(2, 8) = out_2_8;
      out_JF_x_dot(6, 8) = out_6_8;
      out_JF_x_dot(1, 9) = out_1_9;
      out_JF_x_dot(2, 10) = out_2_10;
    end % JF_x_dot
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_v = JF_v( this, in_1, in_2, in_3, t )
      % Evaluate the Jacobian of F with respect to v.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);
      u__1_dot = in_2(1);
      v__1_dot = in_2(2);
      u__2_dot = in_2(3);
      v__2_dot = in_2(4);
      x__1_dot = in_2(5);
      y__1_dot = in_2(6);
      x__2_dot = in_2(7);
      y__2_dot = in_2(8);
      lambda__1_dot = in_2(9);
      lambda__2_dot = in_2(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_JF_v = zeros(10, 0);
    end % JF_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( this, in_1, t )
      % Evaluate the the veils v.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_v = zeros(0, 1);
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jv_x = Jv_x( this, in_1, t )
      % Evaluate the Jacobian of v with respect to x.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_Jv_x = zeros(0, 10);
    end % Jv_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_h = h( this, in_1, in_2, t )
      % Calculate the residual of the invariants h.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      t1 = ell__1 ^ 2;
      t2 = x__1 ^ 2;
      t3 = y__1 ^ 2;
      out_1 = t1 - t2 - t3;
      t4 = ell__2 ^ 2;
      t5 = x__1 * x__2;
      t7 = x__2 ^ 2;
      t8 = y__1 * y__2;
      t10 = y__2 ^ 2;
      out_2 = t4 - t2 - 2 * t5 - t7 - t3 - 2 * t8 - t10;
      t11 = u__1 * x__1;
      t12 = v__1 * y__1;
      out_3 = 2 * t11 + 2 * t12;
      out_4 = 2 * u__1 * x__2 + 2 * u__2 * x__1 + 2 * u__2 * x__2 + 2 * v__1 * y__2 + 2 * v__2 * y__1 + 2 * v__2 * y__2 + 2 * t11 + 2 * t12;
      t23 = u__1 ^ 2;
      t25 = v__1 ^ 2;
      out_5 = -2 / m__1 * (-g * m__1 * y__1 + t23 * m__1 + t25 * m__1 - 2 * lambda__1 * t2 - 2 * lambda__1 * t3);
      t35 = g * m__2;
      t42 = u__2 ^ 2;
      t48 = v__2 ^ 2;
      t62 = 2 * m__2 * u__1 * u__2 + 2 * m__2 * v__1 * v__2 + t23 * m__2 + t25 * m__2 + t42 * m__2 + t48 * m__2 - 2 * lambda__2 * t10 - 2 * lambda__2 * t2 - 2 * lambda__2 * t3 - y__1 * t35 - y__2 * t35 - 4 * lambda__2 * t5 - 2 * lambda__2 * t7 - 4 * lambda__2 * t8;
      out_6 = -2 / m__2 * t62;

      % Store outputs
      out_h = zeros(6, 1);
      out_h(1) = out_1;
      out_h(2) = out_2;
      out_h(3) = out_3;
      out_h(4) = out_4;
      out_h(5) = out_5;
      out_h(6) = out_6;
    end % h
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_x = Jh_x( this, in_1, in_2, t )
      % Calculate the Jacobian of h with respect to x.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      out_3_1 = 2 * x__1;
      out_4_1 = 2 * x__2 + 2 * x__1;
      out_5_1 = -4 * u__1;
      t7 = 0.1e1 / m__2;
      out_6_1 = -2 * t7 * (2 * m__2 * u__1 + 2 * m__2 * u__2);
      out_3_2 = 2 * y__1;
      out_4_2 = 2 * y__2 + 2 * y__1;
      out_5_2 = -4 * v__1;
      out_6_2 = -2 * t7 * (2 * m__2 * v__1 + 2 * m__2 * v__2);
      out_4_3 = out_4_1;
      out_6_3 = out_6_1;
      out_4_4 = out_4_2;
      out_6_4 = out_6_2;
      out_1_5 = -out_3_1;
      out_2_5 = -out_4_3;
      out_3_5 = 2 * u__1;
      out_4_5 = 2 * u__1 + 2 * u__2;
      t20 = 0.1e1 / m__1;
      out_5_5 = 8 * t20 * lambda__1 * x__1;
      out_6_5 = -2 * t7 * (-4 * x__1 * lambda__2 - 4 * x__2 * lambda__2);
      out_1_6 = -out_3_2;
      out_2_6 = -out_4_4;
      out_3_6 = 2 * v__1;
      out_4_6 = 2 * v__1 + 2 * v__2;
      out_5_6 = -2 * t20 * (-g * m__1 - 4 * y__1 * lambda__1);
      out_6_6 = -2 * t7 * (-g * m__2 - 4 * y__1 * lambda__2 - 4 * y__2 * lambda__2);
      out_2_7 = out_2_5;
      out_4_7 = out_4_5;
      out_6_7 = out_6_5;
      out_2_8 = out_2_6;
      out_4_8 = out_4_6;
      out_6_8 = out_6_6;
      t43 = x__1 ^ 2;
      t44 = y__1 ^ 2;
      out_5_9 = -2 * t20 * (-2 * t43 - 2 * t44);
      t52 = x__2 ^ 2;
      t57 = y__2 ^ 2;
      out_6_10 = -2 * t7 * (-4 * x__1 * x__2 - 4 * y__1 * y__2 - 2 * t43 - 2 * t44 - 2 * t52 - 2 * t57);

      % Store outputs
      out_Jh_x = zeros(6, 10);
      out_Jh_x(3, 1) = out_3_1;
      out_Jh_x(4, 1) = out_4_1;
      out_Jh_x(5, 1) = out_5_1;
      out_Jh_x(6, 1) = out_6_1;
      out_Jh_x(3, 2) = out_3_2;
      out_Jh_x(4, 2) = out_4_2;
      out_Jh_x(5, 2) = out_5_2;
      out_Jh_x(6, 2) = out_6_2;
      out_Jh_x(4, 3) = out_4_3;
      out_Jh_x(6, 3) = out_6_3;
      out_Jh_x(4, 4) = out_4_4;
      out_Jh_x(6, 4) = out_6_4;
      out_Jh_x(1, 5) = out_1_5;
      out_Jh_x(2, 5) = out_2_5;
      out_Jh_x(3, 5) = out_3_5;
      out_Jh_x(4, 5) = out_4_5;
      out_Jh_x(5, 5) = out_5_5;
      out_Jh_x(6, 5) = out_6_5;
      out_Jh_x(1, 6) = out_1_6;
      out_Jh_x(2, 6) = out_2_6;
      out_Jh_x(3, 6) = out_3_6;
      out_Jh_x(4, 6) = out_4_6;
      out_Jh_x(5, 6) = out_5_6;
      out_Jh_x(6, 6) = out_6_6;
      out_Jh_x(2, 7) = out_2_7;
      out_Jh_x(4, 7) = out_4_7;
      out_Jh_x(6, 7) = out_6_7;
      out_Jh_x(2, 8) = out_2_8;
      out_Jh_x(4, 8) = out_4_8;
      out_Jh_x(6, 8) = out_6_8;
      out_Jh_x(5, 9) = out_5_9;
      out_Jh_x(6, 10) = out_6_10;
    end % Jh_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_v = Jh_v( this, in_1, in_2, t )
      % Calculate the Jacobian of h with respect to v.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell__1 = this.m_ell__1;
      ell__2 = this.m_ell__2;

      % Extract inputs
      u__1 = in_1(1);
      v__1 = in_1(2);
      u__2 = in_1(3);
      v__2 = in_1(4);
      x__1 = in_1(5);
      y__1 = in_1(6);
      x__2 = in_1(7);
      y__2 = in_1(8);
      lambda__1 = in_1(9);
      lambda__2 = in_1(10);

      % Evaluate function
      % No elements

      % Store outputs
      out_Jh_v = zeros(6, 0);
    end % Jh_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % DoublePendulum

% That's All Folks!
