% +--------------------------------------------------------------------------+
% | 'Indigo' module version 1.0 - BSD 3-Clause License - Copyright (c) 2023  |
% | Current version authors:                                                 |
% |   Davide Stocco and Enrico Bertolazzi.                                   |
% +--------------------------------------------------------------------------+

% Matlab generated code for implicit system: Pendulum
% This file has been automatically generated by Indigo.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef Pendulum < Indigo.DAE.Explicit
  %
  % No class description provided.
  %
  properties (SetAccess = protected, Hidden = true)
    % User data
    m_x__0 = 0;
    m_y__0 = 0;
    m_u__0 = 0;
    m_v__0 = 0;
    m_m = 1.0;
    m_g = 9.81;
    m_ell = 1.0;
  end
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = Pendulum( varargin )
      % Class constructor.

      % Superclass constructor
      num_eqns = 5;
      num_veil = 6;
      num_invs = 4;
      this = this@Indigo.DAE.Explicit('Pendulum', num_eqns, num_veil, num_invs);

      % User data
      if (nargin == 0)
        % Keep default values
      elseif (nargin == 1 && isstruct(varargin{1}))
        this.m_x__0 = varargin{1}.x__0;
        this.m_y__0 = varargin{1}.y__0;
        this.m_u__0 = varargin{1}.u__0;
        this.m_v__0 = varargin{1}.v__0;
        this.m_m = varargin{1}.m;
        this.m_g = varargin{1}.g;
        this.m_ell = varargin{1}.ell;
      elseif (nargin == 7)
        this.m_x__0 = varargin{1};
        this.m_y__0 = varargin{2};
        this.m_u__0 = varargin{3};
        this.m_v__0 = varargin{4};
        this.m_m = varargin{5};
        this.m_g = varargin{6};
        this.m_ell = varargin{7};
      else
        error('wrong number of input arguments.');
      end
    end % Pendulum
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_f = f( this, in_1, in_2, ~ )
      % Evaluate the function f.

      % Extract properties
      m = this.m_m;

      % Extract inputs
      x = in_1(1);
      y = in_1(2);
      u = in_1(3);
      v = in_1(4);
      lambda = in_1(5);
      V_y58KN_1 = in_2(1);

      % Evaluate function
      out_1 = u;
      out_2 = v;
      t1 = lambda * x;
      t2 = 0.1e1 / m;
      out_3 = -2 * t2 * t1;
      out_4 = -V_y58KN_1 * t2;
      t14 = x ^ 2;
      t15 = y ^ 2;
      out_5 = -0.1e1 / (t14 + t15) * (2 * lambda * y * v + 8 * u * t1 + 3 * V_y58KN_1 * v) / 2;

      % Store outputs
      out_f = zeros(5, 1);
      out_f(1) = out_1;
      out_f(2) = out_2;
      out_f(3) = out_3;
      out_f(4) = out_4;
      out_f(5) = out_5;
    end % f
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jf_x = Jf_x( this, in_1, in_2, ~ )
      % Evaluate the Jacobian of f with respect to x.

      % Extract properties
      m = this.m_m;

      % Extract inputs
      x = in_1(1);
      y = in_1(2);
      u = in_1(3);
      v = in_1(4);
      lambda = in_1(5);
      V_y58KN_1 = in_2(1);

      % Evaluate function
      t1 = 0.1e1 / m;
      out_3_1 = -2 * t1 * lambda;
      t5 = x ^ 2;
      t6 = y ^ 2;
      t7 = t5 + t6;
      t8 = 0.1e1 / t7;
      t11 = lambda * x;
      t14 = y * lambda;
      t20 = t7 ^ 2;
      t22 = 0.1e1 / t20 * (8 * u * t11 + 2 * v * t14 + 3 * V_y58KN_1 * v);
      out_5_1 = -4 * t8 * u * lambda + x * t22;
      out_5_2 = -t8 * v * lambda + y * t22;
      out_1_3 = 1;
      out_5_3 = -4 * t8 * t11;
      out_2_4 = 1;
      out_5_4 = -t8 * (2 * t14 + 3 * V_y58KN_1) / 2;
      out_3_5 = -2 * t1 * x;
      out_5_5 = -t8 * (8 * x * u + 2 * y * v) / 2;

      % Store outputs
      out_Jf_x = zeros(5, 5);
      out_Jf_x(3, 1) = out_3_1;
      out_Jf_x(5, 1) = out_5_1;
      out_Jf_x(5, 2) = out_5_2;
      out_Jf_x(1, 3) = out_1_3;
      out_Jf_x(5, 3) = out_5_3;
      out_Jf_x(2, 4) = out_2_4;
      out_Jf_x(5, 4) = out_5_4;
      out_Jf_x(3, 5) = out_3_5;
      out_Jf_x(5, 5) = out_5_5;
    end % Jf_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jf_v = Jf_v( ~, ~, ~, ~ )
      % Evaluate the Jacobian of f with respect to v.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      % No body

      % Store outputs
      out_Jf_v = zeros(5, 6);
    end % Jf_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( this, in_1, ~ )
      % Evaluate the the veils v.

      % Extract properties
      m = this.m_m;
      g = this.m_g;
      ell = this.m_ell;

      % Extract inputs
      x = in_1(1);
      y = in_1(2);
      u = in_1(3);
      v = in_1(4);
      lambda = in_1(5);

      % Evaluate function
      t3 = 2 * y * lambda;
      V_y58KN_1 = g * m + t3;
      t4 = ell ^ 2;
      t5 = x ^ 2;
      t6 = y ^ 2;
      V_y58KN_2 = t4 - t5 - t6;
      V_y58KN_3 = x * u + y * v;
      t12 = u ^ 2;
      t13 = v ^ 2;
      t17 = 0.1e1 / m;
      V_y58KN_4 = t17 * (-y * V_y58KN_1 - 2 * lambda * t5 + (t12 + t13) * m);
      V_y58KN_5 = t17 * (t3 + V_y58KN_1);
      V_y58KN_6 = t17 * (t5 + t6);

      % Store outputs
      out_v = zeros(6, 1);
      out_v(1) = V_y58KN_1;
      out_v(2) = V_y58KN_2;
      out_v(3) = V_y58KN_3;
      out_v(4) = V_y58KN_4;
      out_v(5) = V_y58KN_5;
      out_v(6) = V_y58KN_6;
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jv_x = Jv_x( this, in_1, in_2, ~ )
      % Evaluate the Jacobian of v with respect to x.

      % Extract properties
      m = this.m_m;

      % Extract inputs
      x = in_1(1);
      y = in_1(2);
      u = in_1(3);
      v = in_1(4);
      lambda = in_1(5);
      V_y58KN_1 = in_2(1);

      % Evaluate function
      D_V_y58KN_1_1 = 0;
      D_V_y58KN_2_1 = -2 * x;
      D_V_y58KN_3_1 = u;
      t3 = 0.1e1 / m;
      D_V_y58KN_4_1 = -4 * t3 * lambda * x;
      D_V_y58KN_5_1 = 0;
      D_V_y58KN_6_1 = 2 * t3 * x;
      D_V_y58KN_1_2 = 2 * lambda;
      t7 = 2 * y;
      D_V_y58KN_2_2 = -t7;
      D_V_y58KN_3_2 = v;
      D_V_y58KN_4_2 = -t3 * V_y58KN_1;
      D_V_y58KN_5_2 = 2 * t3 * lambda;
      D_V_y58KN_6_2 = 2 * t3 * y;
      D_V_y58KN_1_3 = 0;
      D_V_y58KN_2_3 = 0;
      D_V_y58KN_3_3 = x;
      D_V_y58KN_4_3 = 2 * u;
      D_V_y58KN_5_3 = 0;
      D_V_y58KN_6_3 = 0;
      D_V_y58KN_1_4 = 0;
      D_V_y58KN_2_4 = 0;
      D_V_y58KN_3_4 = y;
      D_V_y58KN_4_4 = 2 * v;
      D_V_y58KN_5_4 = 0;
      D_V_y58KN_6_4 = 0;
      D_V_y58KN_1_5 = t7;
      D_V_y58KN_2_5 = 0;
      D_V_y58KN_3_5 = 0;
      t11 = x ^ 2;
      D_V_y58KN_4_5 = t3 * (-y * D_V_y58KN_1_2 - 2 * t11);
      D_V_y58KN_5_5 = t3 * (D_V_y58KN_1_2 + D_V_y58KN_1_5);
      D_V_y58KN_6_5 = 0;

      % Store outputs
      out_Jv_x = zeros(6, 5);
      out_Jv_x(1, 1) = D_V_y58KN_1_1;
      out_Jv_x(2, 1) = D_V_y58KN_2_1;
      out_Jv_x(3, 1) = D_V_y58KN_3_1;
      out_Jv_x(4, 1) = D_V_y58KN_4_1;
      out_Jv_x(5, 1) = D_V_y58KN_5_1;
      out_Jv_x(6, 1) = D_V_y58KN_6_1;
      out_Jv_x(1, 2) = D_V_y58KN_1_2;
      out_Jv_x(2, 2) = D_V_y58KN_2_2;
      out_Jv_x(3, 2) = D_V_y58KN_3_2;
      out_Jv_x(4, 2) = D_V_y58KN_4_2;
      out_Jv_x(5, 2) = D_V_y58KN_5_2;
      out_Jv_x(6, 2) = D_V_y58KN_6_2;
      out_Jv_x(1, 3) = D_V_y58KN_1_3;
      out_Jv_x(2, 3) = D_V_y58KN_2_3;
      out_Jv_x(3, 3) = D_V_y58KN_3_3;
      out_Jv_x(4, 3) = D_V_y58KN_4_3;
      out_Jv_x(5, 3) = D_V_y58KN_5_3;
      out_Jv_x(6, 3) = D_V_y58KN_6_3;
      out_Jv_x(1, 4) = D_V_y58KN_1_4;
      out_Jv_x(2, 4) = D_V_y58KN_2_4;
      out_Jv_x(3, 4) = D_V_y58KN_3_4;
      out_Jv_x(4, 4) = D_V_y58KN_4_4;
      out_Jv_x(5, 4) = D_V_y58KN_5_4;
      out_Jv_x(6, 4) = D_V_y58KN_6_4;
      out_Jv_x(1, 5) = D_V_y58KN_1_5;
      out_Jv_x(2, 5) = D_V_y58KN_2_5;
      out_Jv_x(3, 5) = D_V_y58KN_3_5;
      out_Jv_x(4, 5) = D_V_y58KN_4_5;
      out_Jv_x(5, 5) = D_V_y58KN_5_5;
      out_Jv_x(6, 5) = D_V_y58KN_6_5;
    end % Jv_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_h = h( this, in_1, in_2, ~ )
      % Calculate the residual of the invariants h.

      % Extract properties
      y__0 = this.m_y__0;
      u__0 = this.m_u__0;
      v__0 = this.m_v__0;
      m = this.m_m;
      g = this.m_g;

      % Extract inputs
      y = in_1(2);
      u = in_1(3);
      v = in_1(4);
      V_y58KN_2 = in_2(2);
      V_y58KN_3 = in_2(3);
      V_y58KN_4 = in_2(4);

      % Evaluate function
      t1 = u ^ 2;
      t2 = u__0 ^ 2;
      t3 = v ^ 2;
      t4 = v__0 ^ 2;
      out_1 = (t1 - t2 + t3 - t4) * m / 2 + m * g * (y - y__0);
      out_2 = V_y58KN_2;
      out_3 = 2 * V_y58KN_3;
      out_4 = -2 * V_y58KN_4;

      % Store outputs
      out_h = zeros(4, 1);
      out_h(1) = out_1;
      out_h(2) = out_2;
      out_h(3) = out_3;
      out_h(4) = out_4;
    end % h
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_x = Jh_x( this, in_1, ~, ~ )
      % Calculate the Jacobian of h with respect to x.

      % Extract properties
      m = this.m_m;
      g = this.m_g;

      % Extract inputs
      u = in_1(3);
      v = in_1(4);

      % Evaluate function
      out_1_2 = g * m;
      out_1_3 = u * m;
      out_1_4 = v * m;

      % Store outputs
      out_Jh_x = zeros(4, 5);
      out_Jh_x(1, 2) = out_1_2;
      out_Jh_x(1, 3) = out_1_3;
      out_Jh_x(1, 4) = out_1_4;
    end % Jh_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_v = Jh_v( ~, ~, ~, ~ )
      % Calculate the Jacobian of h with respect to v.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      % No body

      % Store outputs
      out_Jh_v = zeros(4, 6);
    end % Jh_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out = in_domain( ~, ~, ~ )
      out = true;
    end % in_domain
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % Pendulum

% That's All Folks!
