%
%> Get the list of available method classes.
%>
%> \return A cell array of strings containing the names of the available
%>         method classes and their corresponding type.
%
function out = IndigoSolversList()
  out = { ...
    ... % Explicit Runge-Kutta Methods
    {'ExplicitEuler',     'Explicit'}; ...
    {'ExplicitMidpoint',  'Explicit'}; ...
    {'Generic2',          'Explicit'}; ...
    {'Generic3',          'Explicit'}; ...
    {'Heun2',             'Explicit'}; ...
    {'Heun3',             'Explicit'}; ...
    {'Ralston2',          'Explicit'}; ...
    {'Ralston3',          'Explicit'}; ...
    {'Ralston4',          'Explicit'}; ...
    {'RK3',               'Explicit'}; ...
    {'RK4',               'Explicit'}; ...
    {'RK38',              'Explicit'}; ...
    {'SSPRK3',            'Explicit'}; ...
    {'Wray3',             'Explicit'}; ...
    ... % Embedded Explicit Runge-Kutta Methods
    {'BogackiShampine23', 'EmbeddedExplicit'}; ...
    {'CashKarp45',        'EmbeddedExplicit'}; ...
    {'DormandPrince54',   'EmbeddedExplicit'}; ...
    {'Fehlberg12',        'EmbeddedExplicit'}; ...
    {'Fehlberg45I',       'EmbeddedExplicit'}; ...
    {'Fehlberg45II',      'EmbeddedExplicit'}; ...
    {'Fehlberg78',        'EmbeddedExplicit'}; ...
    {'HeunEuler21',       'EmbeddedExplicit'}; ...
    {'Merson34',          'EmbeddedExplicit'}; ...
    {'Sarafyan45',        'EmbeddedExplicit'}; ...
    {'Verner65',          'EmbeddedExplicit'}; ...
    {'Zonnenveld45',      'EmbeddedExplicit'}; ...
    ... % Implicit Runge-Kutta Methods
    {'CrankNicolson',     'Implicit'}; ...
    {'GaussLegendre2',    'Implicit'}; ...
    {'GaussLegendre4',    'Implicit'}; ...
    {'GaussLegendre6',    'Implicit'}; ...
    {'ImplicitEuler',     'Implicit'}; ...
    {'ImplicitMidpoint',  'Implicit'}; ...
    {'LobattoIIIA2',      'Implicit'}; ...
    {'LobattoIIIA4',      'Implicit'}; ...
    {'LobattoIIIB2',      'Implicit'}; ...
    {'LobattoIIIB4',      'Implicit'}; ...
    {'LobattoIIIC2',      'Implicit'}; ...
    {'LobattoIIIC4',      'Implicit'}; ...
    {'LobattoIIICS2',     'Implicit'}; ...
    {'LobattoIIICS4',     'Implicit'}; ...
    {'LobattoIIID2',      'Implicit'}; ...
    {'LobattoIIID4',      'Implicit'}; ...
    {'RadauIA3',          'Implicit'}; ...
    {'RadauIA5',          'Implicit'}; ...
    {'RadauIIA3',         'Implicit'}; ...
    {'RadauIIA5',         'Implicit'}; ...
    {'SunGeng5',          'Implicit'}; ...
    ... % Embedded Implicit Runge-Kutta Methods
    {'GaussLegendre34',   'EmbeddedImplicit'}; ...
    {'GaussLegendre56',   'EmbeddedImplicit'}; ...
    {'LobattoIIIA12',     'EmbeddedImplicit'}; ...
    {'LobattoIIIA34',     'EmbeddedImplicit'}; ...
    {'LobattoIIIB12',     'EmbeddedImplicit'}; ...
    {'LobattoIIIB34',     'EmbeddedImplicit'}; ...
    {'LobattoIIIC12',     'EmbeddedImplicit'}; ...
    {'LobattoIIIC34',     'EmbeddedImplicit'}  ...
  };
end