% +--------------------------------------------------------------------------+
% | 'Indigo' module version 1.0 - BSD 3-Clause License - Copyright (c) 2023  |
% | Current version authors:                                                 |
% |   Davide Stocco and Enrico Bertolazzi.                                   |
% +--------------------------------------------------------------------------+

% Matlab generated code for implicit system: Index3
% This file has been automatically generated by Indigo.
% DISCLAIMER: If you need to edit it, do it wisely!

classdef Index3 < Indigo.DAE.Implicit
  %
  % No class description provided.
  %
  properties (SetAccess = protected, Hidden = true)
    % User data
    % No Properties
  end
  %
  methods
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function this = Index3( varargin )
      % Class constructor.

      % Superclass constructor
      num_eqns = 3;
      num_veil = 0;
      num_invs = 3;
      this = this@Indigo.DAE.Implicit('Index3', num_eqns, num_veil, num_invs);
    end % Index3
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_F = F( ~, in_1, in_2, ~, t )
      % Evaluate the function F.

      % Extract properties
      % No properties

      % Extract inputs
      x__1 = in_1(1);
      x__2 = in_1(2);
      x__1_dot = in_2(1);
      x__2_dot = in_2(2);
      x__3_dot = in_2(3);

      % Evaluate function
      t1 = sin(t);
      out_1 = -t1 + x__3_dot + x__2;
      out_2 = -t1 + x__2_dot + x__1;
      t3 = cos(t);
      out_3 = 2 * t1 + t3 - x__1_dot;

      % Store outputs
      out_F = zeros(3, 1);
      out_F(1) = out_1;
      out_F(2) = out_2;
      out_F(3) = out_3;
    end % F
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_x = JF_x( ~, ~, ~, ~, ~ )
      % Evaluate the Jacobian of F with respect to x.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      out_2_1 = 1;
      out_1_2 = 1;

      % Store outputs
      out_JF_x = zeros(3, 3);
      out_JF_x(2, 1) = out_2_1;
      out_JF_x(1, 2) = out_1_2;
    end % JF_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_x_dot = JF_x_dot( ~, ~, ~, ~, ~ )
      % Evaluate the Jacobian of F with respect to x_dot.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      out_3_1 = -1;
      out_2_2 = 1;
      out_1_3 = 1;

      % Store outputs
      out_JF_x_dot = zeros(3, 3);
      out_JF_x_dot(3, 1) = out_3_1;
      out_JF_x_dot(2, 2) = out_2_2;
      out_JF_x_dot(1, 3) = out_1_3;
    end % JF_x_dot
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_JF_v = JF_v( ~, ~, ~, ~, ~ )
      % Evaluate the Jacobian of F with respect to v.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      % No body

      % Store outputs
      out_JF_v = zeros(3, 0);
    end % JF_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_v = v( ~, ~, ~ )
      % Evaluate the the veils v.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      % No body

      % Store outputs
      out_v = zeros(0, 1);
    end % v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jv_x = Jv_x( ~, ~, ~, ~ )
      % Evaluate the Jacobian of v with respect to x.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      % No body

      % Store outputs
      out_Jv_x = zeros(0, 3);
    end % Jv_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_h = h( ~, in_1, ~, t )
      % Calculate the residual of the invariants h.

      % Extract properties
      % No properties

      % Extract inputs
      x__1 = in_1(1);
      x__2 = in_1(2);
      x__3 = in_1(3);

      % Evaluate function
      t1 = cos(t);
      out_1 = t1 - x__3;
      t2 = sin(t);
      out_2 = 2 * t2 - x__2;
      out_3 = -2 * t1 + t2 - x__1;

      % Store outputs
      out_h = zeros(3, 1);
      out_h(1) = out_1;
      out_h(2) = out_2;
      out_h(3) = out_3;
    end % h
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_x = Jh_x( ~, ~, ~, ~ )
      % Calculate the Jacobian of h with respect to x.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      out_3_1 = -1;
      out_2_2 = -1;
      out_1_3 = -1;

      % Store outputs
      out_Jh_x = zeros(3, 3);
      out_Jh_x(3, 1) = out_3_1;
      out_Jh_x(2, 2) = out_2_2;
      out_Jh_x(1, 3) = out_1_3;
    end % Jh_x
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out_Jh_v = Jh_v( ~, ~, ~, ~ )
      % Calculate the Jacobian of h with respect to v.

      % Extract properties
      % No properties

      % Extract inputs

      % Evaluate function
      % No body

      % Store outputs
      out_Jh_v = zeros(3, 0);
    end % Jh_v
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
    function out = in_domain( ~, ~, ~ )
      out = true;
    end % in_domain
    %
    % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %
  end
end % Index3

% That's All Folks!
